# .github/workflows/jacoco.yml
name: Java CI with JaCoCo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Commit and push docs/ with JaCoCo report
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add docs/
        git commit -m "Atualiza relatório JaCoCo em docs/ [ci skip]" || echo "Nada para commitar"

        git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} main

