name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Build and test with Maven
      run: mvn clean verify

    - name: Copia relat처rio JaCoCo para pasta docs/
      run: |
        if [ ! -d target/site/jacoco ]; then
          echo "Relat처rio JaCoCo n찾o encontrado. Abortando."
          exit 1
        fi

        mkdir -p docs
        cp -r target/site/jacoco/* docs/

    - name: Commit and push docs/ with JaCoCo report
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add docs/
        git commit -m "Atualiza relat처rio JaCoCo na pasta docs [ci skip]" || echo "Nothing to commit"

        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/rodolfooliveira-Professor/pratica-java-jacoco.git
        git push origin main
