name: Java CI with JaCoCo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Muito importante para não usar o token automático padrão!

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build and run tests with JaCoCo
      run: mvn clean verify

    - name: Copy JaCoCo report to docs/
      run: |
        mkdir -p docs
        cp -r target/site/jacoco/* docs/

    - name: Commit and push JaCoCo report
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add docs/
        git commit -m "Atualiza relatório JaCoCo em docs/ [ci skip]" || echo "Nada para commitar"

        # Remove remote origin para garantir que git push usará o token correto
        git remote remove origin || true

        # Push direto usando o token pessoal, sem usar origin
        git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} main
